### ISSUE TITLE
Pagination for list

### ISSUE THREAD

**Issue by rupamd** [uxreactor/Library-Management-System#11]
Create javascript function for pagination. The function will take an array of records, page size, page no and return a smaller array of size same as the page size. This pagination function can be used in all the places where we need pagination. 

_Note that the pagination is required only when the array size is more than the page size._

**Comment by pradeepnarvaneni** [comment]
Done

**Comment by rupamd** [comment]
The pagination block is not required when the number of record displayed in the list is less than the page size.
![due_date](https://cloud.githubusercontent.com/assets/16861482/12712464/8e33cdfe-c8ee-11e5-9e79-cdcaf45385bb.jpg)
![new_book](https://cloud.githubusercontent.com/assets/16861482/12712465/8e7edbf0-c8ee-11e5-9b51-ab3209ecb4a9.jpg)
