### ISSUE TITLE
User sessions

### ISSUE THREAD

**Issue by rupamd** [uxreactor/Library-Management-System#14]
Create a php function to check for valid user session by the type of user (Guest, Member and Admin). Create session variables for Member and Admin during successful login process of Member and Admin respectively. This php function can be included in all the pages where authentication is required.

**Comment by vijayaprabhakarkonduri** [comment]
User sessions created

**Comment by rupamd** [comment]
Session variables not working. Unauthorized users have access to the internal pages. 

Step to reproduce the bug.
1. Login as Admin.
2. Copy the url from the browser's address bar. For example. http://localhost/uxr_library/code/our-library.php 
3. Logout.
4. Paste the url back to the address bar.
