### ISSUE TITLE
Our Library - Admin

### ISSUE THREAD

**Issue by rupamd** [uxreactor/Library-Management-System#17]
1. **Restructure GUI tables for Members and Books**. Show two GUI tables one each for Members and Books. Show top 5 books or members [_Enhancement_]
2. **Search functionalities**: #10  [Bug]
3. **Column names**: All the column names in the GUI tables should be in Title Case (First letter of every world should be an uppercase letter) [Enhancement]

**Comment by rupamd** [comment]
JS error in page. @nagalakshmiyarra please look into the issue.

**Comment by nagalakshmiyarra** [comment]
Fixed
1.Restructure GUI tables for members and books
2.Search functionalities
3.All columns names
