### ISSUE TITLE
Add new book view - Admin

### ISSUE THREAD

**Issue by rupamd** [uxreactor/Library-Management-System#20]
1. **Required field**: Display \* (asterix) for single field and a message at the bottom if all fields are mandatory. [_Bug_]
2. **New Category functionalities**: Add New Category option in the Category dropdown. When this option is selected show a textbox next to the dropdown and take a new category. [_Enhancement_]
3. Notification/Feedback: #9  [_Bug_]
4. Cancel actions: #9  [_Bug_]

**Comment by balanarsimharaotanneeru** [comment]
#20 is fixed.
