### ISSUE TITLE
Page Title - Request Menu - Admin pages

### ISSUE THREAD

**Issue by rupamd** [uxreactor/Library-Management-System#23]
The page title are not consistent.
![due_date](https://cloud.githubusercontent.com/assets/16861482/12712523/f82da8ce-c8ee-11e5-93ea-d9ee719d1b40.jpg)
![new_book](https://cloud.githubusercontent.com/assets/16861482/12712526/f836c8d2-c8ee-11e5-916b-effbf70e6d87.jpg)
![new_membership](https://cloud.githubusercontent.com/assets/16861482/12712524/f82fac14-c8ee-11e5-9a2b-e5ad6da61531.jpg)
![request](https://cloud.githubusercontent.com/assets/16861482/12712525/f8333ca8-c8ee-11e5-968d-9f4204be6e69.jpg)

**Comment by nagalakshmiyarra** [comment]
This is done
