### ISSUE TITLE
Apply for Membership

### ISSUE THREAD

**Issue by rupamd** [uxreactor/Library-Management-System#9]
1. **Cancel actions**: The cancel button does not work in Apply for Membership page.
2. **Submit actions**: The submit button should do its job properly. The submit button in the Apply for Membership doesnot save the column fields properly. Check the php function.
3. **Notification/Feedback**: Notification/Feedback is required for all the form submission.

**Comment by balanarsimharaotanneeru** [comment]
Added the acknowledgment messages, Cancel button working, provided the help for membership.
